// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpS-AYczi6hIkIIDyIxw5k_CKVrOghwl4',
    appId: '1:227216983232:web:4441abca3f88f846cd1925',
    messagingSenderId: '227216983232',
    projectId: 'kanver-332718',
    authDomain: 'kanver-332718.firebaseapp.com',
    storageBucket: 'kanver-332718.appspot.com',
    measurementId: 'G-6H47P42H8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6FPRmo2FlxrUU-FgwN_9gGyoHE4n8yLM',
    appId: '1:227216983232:android:567afcc5c3bc2a54cd1925',
    messagingSenderId: '227216983232',
    projectId: 'kanver-332718',
    storageBucket: 'kanver-332718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeMVjMG9xu53wiSxdSL0W5zSj5sfU7ChI',
    appId: '1:227216983232:ios:181d460de15fea3dcd1925',
    messagingSenderId: '227216983232',
    projectId: 'kanver-332718',
    storageBucket: 'kanver-332718.appspot.com',
    iosBundleId: 'com.example.kanverFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeMVjMG9xu53wiSxdSL0W5zSj5sfU7ChI',
    appId: '1:227216983232:ios:3365b39d96c5368ccd1925',
    messagingSenderId: '227216983232',
    projectId: 'kanver-332718',
    storageBucket: 'kanver-332718.appspot.com',
    iosBundleId: 'com.example.kanverFlutterApp.RunnerTests',
  );
}
